# -*- coding: utf-8 -*-







































Square digit chains




A number chain is created by continuously adding the square of the digits in




a number to form a new number until it has been seen before.




For example,




44 → 32 → 13 → 10 → 1 → 1




85 → 89 → 145 → 42 → 20 → 4 → 16 → 37 → 58 → 89




Therefore any chain that arrives at 1 or 89 will become stuck in an endless loop.




What is most amazing is that EVERY starting number will eventually arrive at 1 or 89.




How many starting numbers below ten million will arrive at 89?




    to form a new number.




    For example, if number = 12, next_number() will return 1^2 + 2^2 = 5.




    Therefore, 5 is the next number of the chain.




    >>> next_number(44)




    32




    >>> next_number(10)




    1




    >>> next_number(32)




    13




    For example, if starting number is 44, then the function generates the




    following chain of numbers:




    44 → 32 → 13 → 10 → 1 → 1.




    Once the next number generated is 1 or 89, the function returns whether




    or not the next number generated by next_number() is 1.




    >>> chain(10)




    True




    >>> chain(58)




    False




    >>> chain(1)




    True




    The function accepts a range number and the function checks all the values




    under value number.









    >>> solution(100)




    80




    >>> solution(10000000)




    8581146


