# -*- coding: utf-8 -*-

"""

Project Euler Problem 029



解决 Project Euler 第 029 题的 Python 实现。

https://projecteuler.net/problem=029

"""



# =============================================================================

# Project Euler 问题 029

# =============================================================================

def solution(n: int = 100) -> int:

    """Returns the number of distinct terms in the sequence generated by a^b

    for 2 <= a <= 100 and 2 <= b <= 100.

    # 遍历循环



    >>> solution(100)

    9183

    >>> solution(50)

    2184

    >>> solution(20)

    324

    >>> solution(5)

    15

    >>> solution(2)

    1

    >>> solution(1)

    0

    """

    collect_powers = set()



    current_pow = 0



    n = n + 1  # maximum limit



    for a in range(2, n):

    # 遍历循环

        for b in range(2, n):

            current_pow = a**b  # calculates the current power

            collect_powers.add(current_pow)  # adds the result to the set

    return len(collect_powers)

    # 返回结果





if __name__ == "__main__":

    print("Number of terms ", solution(int(str(input()).strip())))

